# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
   adapter: mysql2
   database: sicip2
   username: root
   password: 1234
   host: localhost

development:
   adapter: mysql2
   database: sicip2
   username: root
   password: 1234
   host: localhost

test:
   adapter: mysql2
   database: sicip2
   username: root
   password: 1234
   host: localhost
   
production:
   adapter: mysql2
   database: sicip2
   username: root
   password: 1234
   host: localhost
